# Site Settings
title: whiteblog-theme
author: Victor Silva

permalink: /:title/ #/:categories/:title/

plugins:
  - jekyll-redirect-from


header_pages:
#  - _pages/about.md
#  - _pages/contact.md
#  - _pages/setup.md
  - _pages/github.md
  - _pages/categories.md

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - whiteblogtheme.gemspec

comments:
  provider               : "disqus" # false (default), "disqus"
  disqus:
    shortname            : "vmsilvamolina"